services:
  - type: web
    name: millemultiplayer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flet run main.py --web --port $PORT
    plan: free
    autoDeploy: true
